variable "region" {}
variable "environment" {}
variable "aws_prefix" {}
variable "lambda_function_handler_name" {}
variable "smtpInfo_Host" {}
variable "smtpInfo_Port" {}
variable "smtpInfo_DisplayName" {}
variable "smtpInfo_Username" {}
variable "smtpInfo_Password" {}
variable "smtpInfo_UseSSL" {}
variable "profile_Name" {}
variable "profile_Email" {}
variable "profile_Contact" {}
variable "profile_LinkedIn" {}
variable "profile_GitHub" {}
variable "profile_WhatsApp" {}
variable "profile_Address" {}
variable "profile_Website" {}
variable "cors_Origins" {}
variable "cors_Methods" {}
variable "tags_deployment_source" {}
variable "tags_reference_owner" {}
variable "tags_reference_domain" {}
variable "tags_reference_subdomain" {}
variable "tags_reference_application" {}
variable "tags_reference_authentication" {}
variable "tags_reference_contact" {}
variable "tags_reference_application_name" {}
