name: CI/CD

on:
  workflow_dispatch:

jobs:
  Replace-Files:
    name: Replace tfvars Files
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "production.tfvars.json"
          json: ${{ secrets.TERRAFORM }}

  CD:
    needs: [Replace-Files]
    name: Terraform Deploy
    uses: somasundar-dev/Deployments/.github/workflows/Terraform.yaml@main
    with:
      tfvars_file: "production.tfvars.json"
      TF_WORKING_DIR: "./Infra"
      run_deployment: false
      run_destroy: false
