name: CI/CD

on:
  workflow_dispatch:

jobs:
  CD:
    name: Terraform Deploy
    uses: somasundar-dev/Deployments/.github/workflows/Terraform.yaml@main
    with:
      tfvars_path: "./Infra/production.tfvars"
      TF_WORKING_DIR: "./Infra"
      run_deployment: false
      run_destroy: false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
